export function slugify(input: string): string {
  return input
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9α-ωάέήίόύώ\s-]/gi, "")
    .replace(/[αά]/gi, "a")
    .replace(/[β]/gi, "v")
    .replace(/[γ]/gi, "g")
    .replace(/[δ]/gi, "d")
    .replace(/[εέ]/gi, "e")
    .replace(/[ζ]/gi, "z")
    .replace(/[ηή]/gi, "i")
    .replace(/[θ]/gi, "th")
    .replace(/[ιίϊΐ]/gi, "i")
    .replace(/[κ]/gi, "k")
    .replace(/[λ]/gi, "l")
    .replace(/[μ]/gi, "m")
    .replace(/[ν]/gi, "n")
    .replace(/[ξ]/gi, "x")
    .replace(/[οό]/gi, "o")
    .replace(/[π]/gi, "p")
    .replace(/[ρ]/gi, "r")
    .replace(/[σς]/gi, "s")
    .replace(/[τ]/gi, "t")
    .replace(/[υύϋΰ]/gi, "y")
    .replace(/[φ]/gi, "f")
    .replace(/[χ]/gi, "ch")
    .replace(/[ψ]/gi, "ps")
    .replace(/[ωώ]/gi, "o")
    .replace(/[^a-z0-9\s-]/g, "")
    .trim()
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 80);
}
